### ISSUE TITLE
Aelf PlayGround service add unit test

### ISSUE THREAD

**Issue by stefanzhou1** [AElfProject/aelf-dapp-factory#17]
### Web

https://github.com/AElfProject/aelf-playground-build-service
### Tasks

- [ ] Service layering
- [ ] controllers unit test
- [ ] server unit test
- [ ] 3 grain unit test
